name: Release

on:
  push:
    branches:
      - "!*"
    tags:
      - "*"

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 8

      - name: Build with Gradle
        run: ./gradlew build --info
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONARCLOUD_TOKEN }}

      - name: Release to Maven Central
        run: ./gradlew --stacktrace -PbintrayUser="${{ secrets.BINTRAY_USER }}" -PbintrayKey="${{ secrets.BINTRAY_KEY }}" -PsonatypeUsername="${{ secrets.SONATYPE_USER }}" -PsonatypePassword="${{ secrets.SONATYPE_PASSWORD }}" -PgpgPassphrase="${{ secrets.GPG_PASSPHRASE }}" assemble bintrayUpload
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONARCLOUD_TOKEN }}

      - name: Create Release Notes
        id: release_notes
        uses: heinrichreimer/github-changelog-generator-action@v2.1.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body: ${{ steps.release_notes.outputs.changelog }}
          draft: false
          prerelease: false